# generated by datamodel-codegen:
#   filename:  tmp62k13pw2.json
#   timestamp: 2026-07-21T23:36:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    constr,
)


class Model(RootModel[Any]):
    root: Any


class Email(
    RootModel[constr(pattern=r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')]
):
    root: constr(pattern=r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')


class EntityType(Enum):
    Human = 'Human'
    Software = 'Software'
    Software_Assisted = 'Software Assisted'


class MethodType(Enum):
    Behavioral = 'Behavioral'
    Intent = 'Intent'
    Remediation = 'Remediation'
    Gate = 'Gate'


class ModeType(Enum):
    Manual = 'Manual'
    Automated = 'Automated'


class Dimensions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    geopolitical: list[str] | None = Field(None, min_length=1)
    groups: list[str] | None = Field(None, min_length=1)
    sensitivity: list[str] | None = Field(None, min_length=1)
    technologies: list[str] | None = Field(None, min_length=1)
    users: list[str] | None = Field(None, min_length=1)


class EntryMapping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entry_id: str = Field(..., alias='entry-id')
    reference_id: str = Field(..., alias='reference-id')
    remarks: str | None = None


class Scope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    in_: Dimensions | None = Field(None, alias='in')
    out: Dimensions | None = None


class AcceptedRisk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    justification: str | None = None
    risk: EntryMapping
    scope: Scope | None = None
    target_id: str | None = Field(None, alias='target-id')


class ArtifactMapping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reference_id: str = Field(..., alias='reference-id')
    remarks: str | None = None


class Datetime(RootModel[AwareDatetime]):
    root: AwareDatetime


class Disposition(Enum):
    Undetermined = 'Undetermined'
    Enforced = 'Enforced'
    Tolerated = 'Tolerated'
    Clear = 'Clear'


class EnforcementStep(RootModel[str]):
    root: str


class Result(Enum):
    Not_Run = 'Not Run'
    Passed = 'Passed'
    Failed = 'Failed'
    Needs_Review = 'Needs Review'
    Not_Applicable = 'Not Applicable'
    Unknown = 'Unknown'


class EnforcementMethodType(Enum):
    Gate = 'Gate'
    Remediation = 'Remediation'


class EvaluationMethodType(Enum):
    Intent = 'Intent'
    Behavioral = 'Behavioral'


class Parameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted_values: list[str] | None = Field(
        None, alias='accepted-values', min_length=1
    )
    description: str
    id: str
    label: str


class ArtifactType(Enum):
    CapabilityCatalog = 'CapabilityCatalog'
    ControlCatalog = 'ControlCatalog'
    GuidanceCatalog = 'GuidanceCatalog'
    ThreatCatalog = 'ThreatCatalog'
    RiskCatalog = 'RiskCatalog'
    Policy = 'Policy'
    MappingDocument = 'MappingDocument'
    Lexicon = 'Lexicon'
    EvaluationLog = 'EvaluationLog'
    EnforcementLog = 'EnforcementLog'
    VectorCatalog = 'VectorCatalog'
    PrincipleCatalog = 'PrincipleCatalog'
    AuditLog = 'AuditLog'


class AssessmentStep(RootModel[str]):
    root: str


class ConfidenceLevel(Enum):
    Undetermined = 'Undetermined'
    Low = 'Low'
    Medium = 'Medium'
    High = 'High'


class EvidenceType(RootModel[ArtifactType | str]):
    root: ArtifactType | str


class Lifecycle(Enum):
    Active = 'Active'
    Draft = 'Draft'
    Deprecated = 'Deprecated'
    Retired = 'Retired'


class AssessmentRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability: list[str] = Field(..., min_length=1)
    id: str
    recommendation: str | None = None
    replaced_by: EntryMapping | None = Field(None, alias='replaced-by')
    state: Lifecycle | None = None
    text: str


class ModType(Enum):
    Add = 'Add'
    Modify = 'Modify'
    Remove = 'Remove'
    Replace = 'Replace'
    Override = 'Override'


class AssessmentRequirementModifier(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability: list[str] | None = Field(None, min_length=1)
    id: str
    modification_rationale: str = Field(..., alias='modification-rationale')
    modification_type: ModType = Field(..., alias='modification-type')
    recommendation: str | None = None
    target_id: str = Field(..., alias='target-id')
    text: str | None = None


class Group(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    id: str
    title: str


class MappingReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    id: str
    title: str
    url: constr(pattern=r'^(https?|file)://[^\s]+$') | None = None
    version: str


class MultiEntryMapping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entries: list[ArtifactMapping] = Field(..., min_length=1)
    reference_id: str = Field(..., alias='reference-id')
    remarks: str | None = None


class Recommendation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str | None = None
    required: bool | None = None
    text: str


class ResultType(Enum):
    Gap = 'Gap'
    Finding = 'Finding'
    Observation = 'Observation'
    Strength = 'Strength'


class Capability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    group: str
    id: str
    title: str


class Constraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    target_id: str = Field(..., alias='target-id')
    text: str


class CatalogImport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessment_requirement_modifications: list[AssessmentRequirementModifier] | None = (
        Field(None, alias='assessment-requirement-modifications', min_length=1)
    )
    constraints: list[Constraint] | None = Field(None, min_length=1)
    exclusions: list[str] | None = Field(None, min_length=1)
    reference_id: str = Field(..., alias='reference-id')


class Control(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessment_requirements: list[AssessmentRequirement] = Field(
        ..., alias='assessment-requirements', min_length=1
    )
    group: str
    guidelines: list[MultiEntryMapping] | None = Field(None, min_length=1)
    id: str
    objective: str
    replaced_by: EntryMapping | None = Field(None, alias='replaced-by')
    state: Lifecycle | None = None
    threats: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class EntryType(Enum):
    Guideline = 'Guideline'
    Statement = 'Statement'
    Control = 'Control'
    AssessmentRequirement = 'AssessmentRequirement'
    Capability = 'Capability'
    Threat = 'Threat'
    Risk = 'Risk'
    Vector = 'Vector'
    Principle = 'Principle'


class Exemption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    reason: str
    redirect: MultiEntryMapping | None = None


class GuidanceType(Enum):
    Standard = 'Standard'
    Regulation = 'Regulation'
    Best_Practice = 'Best Practice'
    Framework = 'Framework'


class Rationale(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goals: list[str] = Field(..., min_length=1)
    importance: str


class Statement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    recommendations: list[str] | None = Field(None, min_length=1)
    text: str
    title: str | None = None


class GuidanceImport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    constraints: list[Constraint] | None = Field(None, min_length=1)
    exclusions: list[str] | None = Field(None, min_length=1)
    reference_id: str = Field(..., alias='reference-id')


class ImplementationDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Datetime | None = None
    notes: str
    start: Datetime


class ImplementationPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enforcement_timeline: ImplementationDetails = Field(
        ..., alias='enforcement-timeline'
    )
    evaluation_timeline: ImplementationDetails = Field(..., alias='evaluation-timeline')
    notification_process: str | None = Field(None, alias='notification-process')


class Imports(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catalogs: list[CatalogImport] | None = Field(None, min_length=1)
    guidance: list[GuidanceImport] | None = Field(None, min_length=1)
    policies: list[ArtifactMapping] | None = Field(None, min_length=1)


class LexiconReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    citation: str
    url: constr(pattern=r'^(https?|file)://[^\s]+$') | None = None


class LexiconTerm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    definition: str
    id: str
    references: list[LexiconReference] | None = Field(None, min_length=1)
    synonyms: list[str] | None = Field(None, min_length=1)
    title: str


class Type(Enum):
    CapabilityCatalog = 'CapabilityCatalog'
    ControlCatalog = 'ControlCatalog'
    GuidanceCatalog = 'GuidanceCatalog'
    ThreatCatalog = 'ThreatCatalog'
    RiskCatalog = 'RiskCatalog'
    Policy = 'Policy'
    MappingDocument = 'MappingDocument'
    Lexicon = 'Lexicon'
    EvaluationLog = 'EvaluationLog'
    EnforcementLog = 'EnforcementLog'
    VectorCatalog = 'VectorCatalog'
    PrincipleCatalog = 'PrincipleCatalog'
    AuditLog = 'AuditLog'


class Strength(RootModel[confloat(ge=1.0, le=10.0)]):
    root: confloat(ge=1.0, le=10.0)


class MappingTarget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability: list[str] | None = Field(None, min_length=1)
    confidence_level: ConfidenceLevel | None = Field(None, alias='confidence-level')
    entry_id: str = Field(..., alias='entry-id')
    rationale: str | None = None
    remarks: str | None = None
    strength: Strength | None = None


class RelationshipType(Enum):
    implements = 'implements'
    implemented_by = 'implemented-by'
    supports = 'supports'
    supported_by = 'supported-by'
    equivalent = 'equivalent'
    subsumes = 'subsumes'
    no_match = 'no-match'
    relates_to = 'relates-to'


class Mapping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    relationship: RelationshipType
    remarks: str | None = None
    source: str
    targets: list[MappingTarget] | None = Field(None, min_length=1)


class TypedMapping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entry_type: EntryType = Field(..., alias='entry-type')
    reference_id: str = Field(..., alias='reference-id')
    remarks: str | None = None


class FieldMappingStrict(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    relationship: RelationshipType
    remarks: str | None = None
    source: str
    targets: list[MappingTarget] | None = Field(None, min_length=1)


class MitigatedRisk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    risk: EntryMapping


class Risks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: list[AcceptedRisk] | None = Field(None, min_length=1)
    mitigated: list[MitigatedRisk] | None = Field(None, min_length=1)


class Principle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    group: str
    id: str
    rationale: str | None = None
    title: str


class Severity(Enum):
    Low = 'Low'
    Medium = 'Medium'
    High = 'High'
    Critical = 'Critical'


class RiskAppetite(Enum):
    Minimal = 'Minimal'
    Low = 'Low'
    Moderate = 'Moderate'
    High = 'High'


class RiskCategory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    appetite: RiskAppetite
    max_severity: Severity | None = Field(None, alias='max-severity')
    description: str
    id: str
    title: str


class Vector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability: list[str] | None = Field(None, min_length=1)
    description: str
    group: str
    id: str
    title: str


class Contact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    affiliation: str | None = None
    email: Email | None = None
    name: str
    social: str | None = None


class Entity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    id: str
    name: str
    type: EntityType
    uri: constr(pattern=r'^https?://[^\s]+$') | None = None
    version: str | None = None


class AssessmentFinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    log: EntryMapping
    plan: EntryMapping | None = None
    requirement: EntryMapping | None = None
    result: Result


class Justification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessments: list[AssessmentFinding] = Field(..., min_length=1)
    exceptions: list[ArtifactMapping] | None = Field(None, min_length=1)


class ActionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    disposition: Disposition
    end: Datetime | None = None
    justification: Justification
    message: str | None = None
    method: EntryMapping
    start: Datetime
    steps: list[EnforcementStep] = Field(..., min_length=1)


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collected_at: Datetime = Field(..., alias='collected-at')
    description: str | None = None
    id: str
    payload: Any | None = None
    type: EvidenceType


class AssessmentLog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability: list[str] = Field(..., min_length=1)
    confidence_level: ConfidenceLevel | None = Field(None, alias='confidence-level')
    description: str
    end: Datetime | None = None
    evidence: list[Evidence] | None = Field(None, min_length=1)
    message: str
    plan: EntryMapping | None = None
    recommendation: str | None = None
    requirement: EntryMapping
    result: Result
    start: Datetime
    steps: list[AssessmentStep] = Field(..., min_length=1)
    steps_executed: int | None = Field(None, alias='steps-executed')


class AuditResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criteria_reference: MultiEntryMapping = Field(..., alias='criteria-reference')
    description: str
    evidence: list[Evidence] | None = Field(None, min_length=1)
    id: str
    recommendations: list[Recommendation] | None = Field(None, min_length=1)
    title: str
    type: ResultType


class RACI(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountable: list[Contact] = Field(..., min_length=1)
    consulted: list[Contact] | None = Field(None, min_length=1)
    informed: list[Contact] | None = Field(None, min_length=1)
    responsible: list[Contact] = Field(..., min_length=1)


class Resource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environment: str | None = None
    owner: Contact | None = None
    description: str | None = None
    id: str
    name: str
    type: EntityType
    uri: constr(pattern=r'^https?://[^\s]+$') | None = None
    version: str | None = None


class AssessmentLogs(RootModel[list[AssessmentLog]]):
    root: list[AssessmentLog]


class ControlEvaluation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessment_logs: AssessmentLogs = Field(..., alias='assessment-logs')
    control: EntryMapping
    message: str
    name: str
    result: Result


class Guideline(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability: list[str] | None = Field(None, min_length=1)
    extends: EntryMapping | None = None
    group: str
    id: str
    objective: str
    principles: list[MultiEntryMapping] | None = Field(None, min_length=1)
    rationale: Rationale | None = None
    recommendations: list[str] | None = Field(None, min_length=1)
    replaced_by: EntryMapping | None = Field(None, alias='replaced-by')
    see_also: list[str] | None = Field(None, alias='see-also', min_length=1)
    state: Lifecycle | None = None
    statements: list[Statement] | None = Field(None, min_length=1)
    title: str
    vectors: list[MultiEntryMapping] | None = Field(None, min_length=1)


class Risk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    group: str
    id: str
    impact: str | None = None
    owner: RACI | None = None
    rank: int | None = None
    severity: Severity
    threats: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class Actor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contact: Contact | None = None
    description: str | None = None
    id: str
    name: str
    type: EntityType
    uri: constr(pattern=r'^https?://[^\s]+$') | None = None
    version: str | None = None


class AcceptedMethod(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    executor: Actor | None = None
    id: str
    mode: ModeType
    required: bool | None = None
    type: MethodType


class EvaluationMethod(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    executor: Actor | None = None
    id: str
    mode: ModeType
    required: bool | None = None
    type: EvaluationMethodType


class AssessmentPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evaluation_methods: list[EvaluationMethod] = Field(
        ..., alias='evaluation-methods', min_length=1
    )
    evidence_requirements: str | None = Field(None, alias='evidence-requirements')
    frequency: str
    id: str
    parameters: list[Parameter] | None = Field(None, min_length=1)
    requirement_id: str = Field(..., alias='requirement-id')


class EnforcementMethod(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    executor: Actor | None = None
    id: str
    mode: ModeType
    required: bool | None = None
    type: EnforcementMethodType


class Adherence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessment_plans: list[AssessmentPlan] | None = Field(
        None, alias='assessment-plans', min_length=1
    )
    enforcement_methods: list[EnforcementMethod] | None = Field(
        None, alias='enforcement-methods', min_length=1
    )
    evaluation_methods: list[EvaluationMethod] | None = Field(
        None, alias='evaluation-methods', min_length=1
    )
    non_compliance: str | None = Field(None, alias='non-compliance')


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability_groups: list[Group] | None = Field(
        None, alias='applicability-groups', min_length=1
    )
    author: Actor
    date: Datetime | None = None
    description: str
    draft: bool | None = None
    gemara_version: str = Field(..., alias='gemara-version')
    id: str
    lexicon: ArtifactMapping | None = None
    mapping_references: list[MappingReference] | None = Field(
        None, alias='mapping-references', min_length=1
    )
    type: ArtifactType
    version: str | None = None


class AuditLog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criteria: list[ArtifactMapping] = Field(..., min_length=1)
    metadata: Metadata
    owner: RACI | None = None
    results: list[AuditResult] = Field(..., min_length=1)
    summary: str
    target: Resource


class Catalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extends: list[ArtifactMapping] | None = None
    groups: list[Group] | None = Field(None, min_length=1)
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    metadata: Metadata
    title: str


class CapabilityCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[Capability] | None = Field(None, min_length=1)
    metadata: Metadata
    extends: list[ArtifactMapping] | None = None
    groups: list[Group] | None = Field(None, min_length=1)
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class ControlCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    controls: list[Control] | None = Field(None, min_length=1)
    metadata: Metadata
    extends: list[ArtifactMapping] | None = None
    groups: list[Group] | None = Field(None, min_length=1)
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class EnforcementLog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[ActionResult] = Field(..., min_length=1)
    disposition: Disposition
    metadata: Metadata
    target: Resource


class EvaluationLog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evaluations: list[ControlEvaluation] = Field(..., min_length=1)
    metadata: Metadata
    result: Result
    target: Resource


class GuidanceCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exemptions: list[Exemption] | None = Field(None, min_length=1)
    front_matter: str | None = Field(None, alias='front-matter')
    guidelines: list[Guideline] | None = Field(None, min_length=1)
    metadata: Metadata
    type: GuidanceType
    extends: list[ArtifactMapping] | None = None
    groups: list[Group] | None = Field(None, min_length=1)
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class Metadata2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability_groups: list[Group] | None = Field(
        None, alias='applicability-groups', min_length=1
    )
    author: Actor
    date: Datetime | None = None
    description: str
    draft: bool | None = None
    gemara_version: str = Field(..., alias='gemara-version')
    id: str
    lexicon: ArtifactMapping | None = None
    mapping_references: list[MappingReference] | None = Field(
        None, alias='mapping-references', min_length=1
    )
    type: Literal['Lexicon']
    version: str | None = None


class Lexicon(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: Metadata2
    terms: list[LexiconTerm] = Field(..., min_length=1)
    title: str


class Metadata3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability_groups: list[Group] | None = Field(
        None, alias='applicability-groups', min_length=1
    )
    author: Actor
    date: Datetime | None = None
    description: str
    draft: bool | None = None
    gemara_version: str = Field(..., alias='gemara-version')
    id: str
    lexicon: ArtifactMapping | None = None
    mapping_references: list[MappingReference] = Field(
        ..., alias='mapping-references', min_length=1
    )
    type: Literal['MappingDocument']
    version: str | None = None


class MappingDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mappings: list[FieldMappingStrict] = Field(..., min_length=1)
    metadata: Metadata3
    remarks: str | None = None
    source_reference: TypedMapping = Field(..., alias='source-reference')
    target_reference: TypedMapping = Field(..., alias='target-reference')
    title: str


class Metadata4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applicability_groups: list[Group] | None = Field(
        None, alias='applicability-groups', min_length=1
    )
    author: Actor
    date: Datetime | None = None
    description: str
    draft: bool | None = None
    gemara_version: str = Field(..., alias='gemara-version')
    id: str
    lexicon: ArtifactMapping | None = None
    mapping_references: list[MappingReference] | None = Field(
        None, alias='mapping-references', min_length=1
    )
    type: Literal['Policy']
    version: str | None = None


class Policy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adherence: Adherence | None = None
    contacts: RACI
    implementation_plan: ImplementationPlan | None = Field(
        None, alias='implementation-plan'
    )
    imports: Imports | None = None
    metadata: Metadata4
    risks: Risks | None = None
    scope: Scope | None = None
    title: str


class PrincipleCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: Metadata
    principles: list[Principle] | None = Field(None, min_length=1)
    extends: list[ArtifactMapping] | None = None
    groups: list[Group] | None = Field(None, min_length=1)
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class RiskCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    groups: list[RiskCategory] | None = Field(None, min_length=1)
    metadata: Metadata
    risks: list[Risk] | None = Field(None, min_length=1)
    extends: list[ArtifactMapping] | None = None
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class Threat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actors: list[Actor] | None = Field(None, min_length=1)
    capabilities: list[MultiEntryMapping] = Field(..., min_length=1)
    description: str
    group: str
    id: str
    title: str
    vectors: list[MultiEntryMapping] | None = Field(None, min_length=1)


class ThreatCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: Metadata
    threats: list[Threat] | None = Field(None, min_length=1)
    extends: list[ArtifactMapping] | None = None
    groups: list[Group] | None = Field(None, min_length=1)
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class VectorCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: Metadata
    vectors: list[Vector] | None = Field(None, min_length=1)
    extends: list[ArtifactMapping] | None = None
    groups: list[Group] | None = Field(None, min_length=1)
    imports: list[MultiEntryMapping] | None = Field(None, min_length=1)
    title: str


class Log(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: Metadata
    target: Resource
